### PR TITLE
Improve module and script measurements

### PR DESCRIPTION
**Pull request by lindi2**

### CODE REVIEW

**Comment by neusdan** [comment]
Looks good, thanks a lot. I'll try to test and merge it this week.

**Comment by lindi2** [comment]
Ping? I'd like to continue fixing this but I'd rather see these changes included first...

**Comment by lindi2** [comment]
Ping? These improvements are essential if you want to ensure that the whole boot process is actually measured.

**Comment by securitykernel** [comment]
Thanks for your contribution! Unfortunately, we decided to deprecate and no longer maintain this project. I will be closing this issue.

**Pull request closed without merging**
